common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5000
    log:
        conf: "logging_dev.yaml"
    aws:
        url: "https://{}.s3-ap-northeast-1.amazonaws.com/{}"
postgres:
    url: "postgresql://"
    host: "localhost"
    port: 5432
    user: "thingaha"
    password: "thingaha"
    db: "thingaha_dev"
